# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumKochavaExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumKochavaExample
  
  ### NOTE!!! Update below to TealiumKochava pod
  pod 'TealiumKochava', :path=> '/Users/christina/Projects/work-repos/github/tealium-ios-kochava-remote-command'
  pod 'tealium-swift/TealiumLogger', '~> 1.9'
  pod 'tealium-swift/TealiumTagManagement', '~> 1.9'
  pod 'tealium-swift/TealiumAppData', '~> 1.9'
  pod 'tealium-swift/TealiumDeviceData', '~> 1.9'
  pod 'tealium-swift/TealiumLifecycle', '~> 1.9'

end
