# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'TealiumKochavaExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumKochavaExample
  
  pod 'TealiumKochava', :path=> '../'
  pod 'tealium-swift/Lifecycle', '~> 2.6'

end
